services:
  ? internal-ui-frontend-manual-test-2
  : build:
      context: .
      target: production
    image: internal-ui-frontend-manual-test-2
    container_name: internal-ui-frontend-manual-test-2
    environment:
      APPINSIGHTS_CLOUDROLE: internal-ui-frontend-manual-test-2-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
