# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ? internal-ui-frontend-manual-test-2
  : build:
      target: development
    image: internal-ui-frontend-manual-test-2-development
    container_name: internal-ui-frontend-manual-test-2-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
