# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ? internal-ui-frontend-manual-test-2
  : build:
      target: development
    image: internal-ui-frontend-manual-test-2-development
    container_name: internal-ui-frontend-manual-test-2-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
