{{- include "adp-helm-library.deployment" (list . "internal-ui-frontend-manual-test-2.deployment") -}}
{{- define "internal-ui-frontend-manual-test-2.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "adp-helm-library.container" (list . "internal-ui-frontend-manual-test-2.container") }}
{{- end -}}
